@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Glossary *-right-> "1" UniqueFlashCardList
Glossary *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueFlashCardList
UniqueTagList -[hidden]down- UniqueFlashCardList

UniqueTagList *-right-> "*" Tag
UniqueFlashCardList o-right-> FlashCard

FlashCard -up-> "*" Tag

FlashCard *--> GermanPhrase
FlashCard *--> EnglishPhrase
FlashCard *--> Difficulty
@enduml
