@startuml
start
:User executes Add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Difficulty specified])
    if () then ([Valid difficulty])
    :Add specified difficulty tag;
    else ([else])
        stop
    endif
   else ([else])
       : Add default Medium difficulty tag;
endif
stop
@enduml
