@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyGlossary <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Glossary
Class ReadOnlyGlossary
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package FlashCard {
Class FlashCard
Class Order
Class Difficulty
Class Gender
Class GermanPhrase
Class EnglishPhrase
Class UniqueFlashCardList
}

Package Score {
Class Score
Class UniqueScoreList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Glossary .up.|> ReadOnlyGlossary

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Glossary
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Glossary *--> "1" UniqueFlashCardList
UniqueFlashCardList o--> "*" FlashCard
FlashCard *--> GermanPhrase
FlashCard *--> EnglishPhrase
FlashCard *--> Difficulty
FlashCard *--> Gender
FlashCard *--> Order
FlashCard *--> "*" Tag

UniqueScoreList o-left-> "*" Score
Score *--> "1..*" FlashCard

GermanPhrase -[hidden]right-> EnglishPhrase
EnglishPhrase -[hidden]right-> Difficulty
Difficulty -[hidden]right-> Gender

ModelManager -->"1" FlashCard : filtered list
@enduml
