@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface "ObjectStorage<ReadOnlyGlossary>" <<Interface>>
Interface "ObjectStorage<ReadOnlyScoreList>" <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonGlossaryStorage
Class JsonScoreStorage
Class JsonScoreList
Class JsonAdaptedScore

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o-down-> "ObjectStorage<ReadOnlyGlossary>"
StorageManager o-up-> "ObjectStorage<ReadOnlyScoreList>"

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonGlossaryStorage .left.|> "ObjectStorage<ReadOnlyGlossary>"
JsonGlossaryStorage .down.> JsonSerializableGlossaryStorage
JsonSerializableGlossaryStorage .right.> JsonAdaptedFlashcard
JsonAdaptedFlashcard .right.> JsonAdaptedTag

JsonScoreStorage .left.|> "ObjectStorage<ReadOnlyScoreList>"
JsonScoreStorage .right.> JsonScoreList
JsonScoreList .down.> JsonAdaptedScore
JsonAdaptedScore .down.> JsonAdaptedFlashcard
@enduml
