@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GlossaryBookParser" as GlossaryBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedGlossary" as VersionedGlossary MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> GlossaryBookParser : parseCommand(undo)
activate GlossaryBookParser

create UndoCommand
GlossaryBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> GlossaryBookParser
deactivate UndoCommand

GlossaryBookParser --> LogicManager : u
deactivate GlossaryBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoGlossary()
activate Model

Model -> VersionedGlossary : undo()
activate VersionedGlossary

VersionedGlossary -> VersionedGlossary :resetData(ReadOnlyGlossary)
VersionedGlossary --> Model :
deactivate VersionedGlossary

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
